# Generated by Django 4.2.10 on 2024-05-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_videogame_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='videogame_covers/'),
        ),
    ]
