# Generated by Django 5.0.2 on 2024-05-21 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
    ]
